name: Publish Module Files, Questions and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'src/raw/**'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: choice
        options:
          - 'true'
          - 'false'
        required: false
        default: 'false'
      delete_docs:
        description: 'Delete docs module'
        type: choice
        options:
          - 'true'
          - 'false'
        required: false
        default: 'true'

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self repo
        uses: actions/checkout@v4

      - name: Checkout Codiquest
        uses: actions/checkout@v4
        with:
          repository: 'moiseslodeiro/codiquest'
          path: 'codiquest'
          ref: 'main'

      - name: Installing node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: List local resources
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          ls -lR src
          ls -lR static

      - name: Copy resources to Codiquest
        run: |
          cp -r src/* codiquest/src/
          cp -r static/* codiquest/static/

      - name: Check resources on Codiquest
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          ls -lR codiquest/src/raw/
          ls -lR codiquest/static

      - name: Installing dependencies
        run: npm install
        working-directory: './codiquest'

      - name: Parsing modules
        run: npm run module:all
        working-directory: './codiquest'
        env:
          PUBLIC: 'true'

      - name: Parsing tests
        run: npm run convert:all
        working-directory: './codiquest'

      - name: Check modules before build
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          ls -lR ./codiquest/src/modules

      - name: Clean docs module
        if: ${{ github.event.inputs.delete_docs == 'true' }}
        run: |
          npm run clean:doc
          rm -rf src/modules/docs.js
        working-directory: './codiquest'

      - name: Create build folder
        run: npm run build
        working-directory: './codiquest'

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./codiquest/build
          publish_branch: gh-pages
          force_orphan: true
